version: '3'
services:
  web:
    image: elegy/tempest.web.arm7:latest
    ports:
      - '5200:80'
    depends_on:
      - 'api'
    restart: 'always'
  api:
    image: elegy/tempest.api.arm7:latest
    ports:
      - '5050:5000'
    environment:
      - ConnectionString=Server=db;Database=tempest;Password=;User Id=postgres;Port=5466
    depends_on:
      - 'db'
    restart: 'always'
  db:
    image: postgres:10.1
    ports:
      - '5466:5432'
    environment:
      POSTGRES_DB: tempest
    restart: 'always'
